#!/usr/bin/env python3

from enum import Enum

class Item(Enum):
    Vehicle = 1
    Trap = 2
    Crystal = 3

class Game(Enum):
    Spyro_Adventure = 1
    Giants = 2
    Swap_Force = 3
    Trap_Team = 4
    Superchargers = 5
    Imaginators = 6

class Element(Enum):
    Air = 1
    Dark = 2
    Earth = 3
    Fire = 4
    Life = 5
    Light = 6
    Magic = 7
    Tech = 8
    Undead = 9
    Water = 10
    UNKNOWN = 11

class Character():
    Armored_Riptide      = 'Armored Riptide'
    Astroblast_Skylanders_Figure = 'Astroblast Skylanders Figure'
    Astroblast_Skylanders_Superchargers_Figure = 'Astroblast Skylanders Superchargers Figure'
    Autism_Skylander_Power_Blue_Splat = 'Autism Skylander Power Blue Splat'
    Autism_Skylander_Power_Blue_Trigger_Happy = 'Autism Skylander Power Blue Trigger Happy'
    Barkley              = 'Barkley'
    Bash                 = 'Bash'
    Bat_Spin             = 'Bat Spin'
    Big_Buggle_Pop_Fizz  = 'Big Buggle Pop Fizz'
    Birthday_Bash_Big_Bubble_Pop_Fizz = 'Birthday Bash Big Bubble Pop Fizz'
    Blackout             = 'Blackout'
    Blades               = 'Blades'
    Blast_Zone           = 'Blast Zone'
    Blastermind          = 'Blastermind'
    Bone_Bash_Roller_Brawl = 'Bone Bash Roller Brawl'
    Boom_Jet             = 'Boom Jet'
    Boomer               = 'Boomer'
    Bop                  = 'Bop'
    Bouncer              = 'Bouncer'
    Breeze               = 'Breeze'
    Bumble_Blast         = 'Bumble Blast'
    Bushwhack            = 'Bushwhack'
    Camo                 = 'Camo'
    Chill                = 'Chill'
    Chop_Chop            = 'Chop Chop'
    Chopper              = 'Chopper'
    Cobra_Cadabra        = 'Cobra Cadabra'
    Countdown            = 'Countdown'
    Crusher              = 'Crusher'
    Cynder               = 'Cynder'
    Deep_Dive_Gill_Grunt = 'Deep Dive Gill Grunt'
    Deja_Vu              = 'Deja Vu'
    Dino_Rang            = 'Dino Rang'
    Dive_Clops           = 'Dive Clops'
    Doom                 = 'Doom'
    Double_Dare_Trigger_Happy = 'Double Dare Trigger Happy'
    Double_Trouble       = 'Double Trouble'
    Drill_Sergeant       = 'Drill Sergeant'
    Drobit               = 'Drobit'
    Drobot               = 'Drobot'
    Dune_Bug             = 'Dune Bug'
    Echo                 = 'Echo'
    Eggcited_Thrillipede = 'Eggcited Thrillipede'
    Eggsellent_Weeruptor = 'Eggsellent Weeruptor'
    Enigma               = 'Enigma'
    Eruptor              = 'Eruptor'
    Eruptor_Lava_Barf    = 'Eruptor Lava Barf'
    Eruptor_Volcanic_Lava_Barf = 'Eruptor Volcanic Lava Barf'
    Eye_Brawl            = 'Eye Brawl'
    Eye_Small            = 'Eye Small'
    Fiesta               = 'Fiesta'
    Fire_Kraken          = 'Fire Kraken'
    Fist_Bump            = 'Fist Bump'
    Flame_Fire_Bone_Hot_Dog = 'Flame Fire Bone Hot Dog'
    Flameslinger         = 'Flameslinger'
    Flashwing            = 'Flashwing'
    Fling_Kong           = 'Fling Kong'
    Flip_Wreck           = 'Flip Wreck'
    Food_Fight           = 'Food Fight'
    Free_Ranger          = 'Free Ranger'
    Freeze_Blade         = 'Freeze Blade'
    Fright_Rider         = 'Fright Rider'
    Frightful_Fiesta     = 'Frightful Fiesta'
    Fryno                = 'Fryno'
    Funny_Bone           = 'Funny Bone'
    Gearshift            = 'Gearshift'
    Ghost_Roaster        = 'Ghost Roaster'
    Gill_Grunt           = 'Gill Grunt'
    Gill_Runt            = 'Gill Runt'
    Gnarly_Tree_Rex      = 'Gnarly Tree Rex'
    Gold_Stink_Bomb      = 'Gold Stink Bomb'
    Granite_Crusher      = 'Granite Crusher'
    Grilla_Drilla        = 'Grilla Drilla'
    Grim_Creeper         = 'Grim Creeper'
    Gusto                = 'Gusto'
    Halloween_Fright_Rider = 'Halloween Fright Rider'
    Hammer_Slam_Bowser   = 'Hammer Slam Bowser'
    Hammer_Slammer_Bowser = 'Hammer Slammer Bowser'
    Head_Rush            = 'Head Rush'
    Hex                  = 'Hex'
    High_Five            = 'High Five'
    High_Volt            = 'High Volt'
    Hijinx               = 'Hijinx'
    Hoot_Loop            = 'Hoot Loop'
    Hot_Dog              = 'Hot Dog'
    Hot_Head             = 'Hot Head'
    Hurricane_Jet_Vac    = 'Hurricane Jet Vac'
    Ignitor              = 'Ignitor'
    Jawbreaker           = 'Jawbreaker'
    Jet_Vac              = 'Jet Vac'
    Jini                 = 'Jini'
    Kaboom               = 'Kaboom'
    Knight_Light         = 'Knight Light'
    Knight_Mare          = 'Knight Mare'
    Krypt_King           = 'Krypt King'
    Lava_Lance_Eruptor   = 'Lava Lance Eruptor'
    Lightning_Rod        = 'Lightning Rod'
    Lob_Star             = 'Lob Star'
    Magna_Charge         = 'Magna Charge'
    Minijini             = 'Minijini'
    Missle_Tow_Dive_Clops = 'Missle Tow Dive Clops'
    Night_Shift          = 'Night Shift'
    Nightfall            = 'Nightfall'
    Ninjini              = 'Ninjini'
    Ninjini_Scarlet      = 'Ninjini Scarlet'
    Pet_Vac              = 'Pet Vac'
    Pop_Fizz             = 'Pop Fizz'
    Pop_Thorn            = 'Pop Thorn'
    Prism_Break          = 'Prism Break'
    Prism_Break_2012_Gift = 'Prism Break 2012 Gift'
    Pumpkin_Eye_Brawl    = 'Pumpkin Eye Brawl'
    Punk_Shock           = 'Punk Shock'
    Rattle_Shake         = 'Rattle Shake'
    Riptide              = 'Riptide'
    Rollerbrawl          = 'Rollerbrawl'
    Rubble_Rouser        = 'Rubble Rouser'
    Scorp                = 'Scorp'
    Scratch              = 'Scratch'
    Shark_Shooter_Terrafin = 'Shark Shooter Terrafin'
    Short_Cut            = 'Short Cut'
    Shroomboom           = 'Shroomboom'
    Slam_Bam             = 'Slam Bam'
    Slobber_Tooth        = 'Slobber Tooth'
    Small_Fry            = 'Small Fry'
    Smash_Hit            = 'Smash Hit'
    Smolderdash          = 'Smolderdash'
    Snap_Shot            = 'Snap Shot'
    Snow_Brite_Stormblade = 'Snow Brite Stormblade'
    Snowderdash          = 'Snowderdash'
    Sonic_Boom           = 'Sonic Boom'
    Spitfire             = 'Spitfire'
    Splat                = 'Splat'
    Spotlight            = 'Spotlight'
    Sprocket             = 'Sprocket'
    Spry                 = 'Spry'
    Spy_Rise             = 'Spy Rise'
    Spyro                = 'Spyro'
    Star_Strike          = 'Star Strike'
    Stealth_Elf          = 'Stealth Elf'
    Steel_Plated_Smash_Hit = 'Steel Plated Smash Hit'
    Stink_Bomb           = 'Stink Bomb'
    Stormblade           = 'Stormblade'
    Stump_Smash          = 'Stump Smash'
    Sunburn              = 'Sunburn'
    Super_Shot_Stealth_Elf = 'Super Shot Stealth Elf'
    Swarm                = 'Swarm'
    Terrabite            = 'Terrabite'
    Terrafin             = 'Terrafin'
    Thrillipede          = 'Thrillipede'
    Thumpback            = 'Thumpback'
    Thumpling            = 'Thumpling'
    Thunderbolt          = 'Thunderbolt'
    Torch                = 'Torch'
    Trail_Blazer         = 'Trail Blazer'
    Trap_Shadow          = 'Trap Shadow'
    Tread_Head           = 'Tread Head'
    Tree_Rex             = 'Tree Rex'
    Trigger_Happy        = 'Trigger Happy'
    Trigger_Snappy       = 'Trigger Snappy'
    Tuff_Luck            = 'Tuff Luck'
    Turbo_Charge_Donkey_Kong = 'Turbo Charge Donkey Kong'
    Voodood              = 'Voodood'
    Wallop               = 'Wallop'
    Warnado              = 'Warnado'
    Wash_Buckler         = 'Wash Buckler'
    Weeruptor            = 'Weeruptor'
    Wham_Shell           = 'Wham Shell'
    Whirlwind            = 'Whirlwind'
    Whisper_Elf          = 'Whisper Elf'
    Wild_Fire            = 'Wild Fire'
    Wildfire             = 'Wildfire'
    Wind_Up              = 'Wind Up'
    Wrecking_Ball        = 'Wrecking Ball'
    Zap                  = 'Zap'
    Zoo_Lou              = 'Zoo Lou'
    Zook                 = 'Zook'

class Tag(Enum):
    Metallic = 0
    Clear = 1
    Gold = 2
    Silver = 3
    Chrome = 4
    Glow_In_Dark = 5
    Dark = 6
    Royal = 7
    Legendary = 8
    Red = 9
    Green = 10
    Blue = 11
    Flocked = 12
    Lightcore = 13
    Toy_Fair = 14
    Sparkle = 15
    Glitter = 16
    Stone = 17
    Molten = 18
    Color_Shift = 19
    Violet = 20
    Enchanted = 21
    Polar = 22
    Mini = 23
    Fluffy = 24
    Springtime = 25
    Sidekick = 26
    Purple = 27
    Silver_Bronze_Variant = 28
    Quickdraw = 29
    Winterfest = 30
    Power_Punch = 31
    Punch = 32
    Kickoff = 33
    Nitro = 34
    Love_Potion = 35
    Heavy_Duty = 36
    Jolly = 37
    Thorn_Horn = 38
    Mega_Ram = 39
    Jade = 40
    Pearl = 41
    Glowindark = 99

class Figurine(Enum):
    Lightning_Rod                  = ('Lightning Rod'               , Game.Spyro_Adventure  , Element.Air    , Character.Lightning_Rod            , '0300', '0000', 'spyro/lightning-rod.jpg', [])
    Dino_Rang                      = ('Dino Rang'                   , Game.Spyro_Adventure  , Element.Earth  , Character.Dino_Rang                , '0600', '0000', 'spyro/dino-rang.jpg'    , [])
    Terrabite                      = ('Terrabite'                   , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Terrabite                , 'FFFF', 'FFFF', 'spyro/terrabite.jpg'    , [])
    Double_Trouble                 = ('Double Trouble'              , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Double_Trouble           , 'FFFF', 'FFFF', 'spyro/double-trouble.jpg', [])
    Camo                           = ('Camo'                        , Game.Spyro_Adventure  , Element.Life   , Character.Camo                     , '1800', '0000', 'spyro/camo.jpg'         , [])
    Spyro                          = ('Spyro'                       , Game.Spyro_Adventure  , Element.Magic  , Character.Spyro                    , '1000', '0000', 'spyro/spyro.jpg'        , [])
    Gill_Grunt_Green               = ('Gill Grunt Green'            , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Gill_Grunt               , 'FFFF', 'FFFF', 'spyro/gill-grunt-green.jpg', [Tag.Green])
    Wham_Shell                     = ('Wham Shell'                  , Game.Spyro_Adventure  , Element.Water  , Character.Wham_Shell               , '0d00', '0000', 'spyro/wham-shell.jpg'   , [])
    Boomer                         = ('Boomer'                      , Game.Spyro_Adventure  , Element.Tech   , Character.Boomer                   , '1600', '0000', 'spyro/boomer.jpg'       , [])
    Drill_Sergeant_Gold            = ('Drill Sergeant Gold'         , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Drill_Sergeant           , 'FFFF', 'FFFF', 'spyro/drill-sergeant-gold.jpg', [Tag.Gold])
    Drobot                         = ('Drobot'                      , Game.Spyro_Adventure  , Element.Tech   , Character.Drobot                   , '1400', '0000', 'spyro/drobot.jpg'       , [])
    Silver_Dino_Rang               = ('Silver Dino Rang'            , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Dino_Rang                , 'FFFF', 'FFFF', 'spyro/silver-dino-rang.jpg', [Tag.Silver])
    Stump_Smash                    = ('Stump Smash'                 , Game.Spyro_Adventure  , Element.Life   , Character.Stump_Smash              , '1b00', '0000', 'spyro/stump-smash.jpg'  , [])
    Trigger_Snappy                 = ('Trigger Snappy'              , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Trigger_Snappy           , 'FFFF', 'FFFF', 'spyro/trigger-snappy.jpg', [])
    Hex                            = ('Hex'                         , Game.Spyro_Adventure  , Element.Undead , Character.Hex                      , '1d00', '0000', 'spyro/hex.jpg'          , [])
    Spyro_Series_1_Chrome          = ('Spyro Series 1 Chrome'       , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Spyro                    , 'FFFF', 'FFFF', 'spyro/spyro-series-1-chrome.jpg', [Tag.Chrome])
    Silver_Eruptor                 = ('Silver Eruptor'              , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Eruptor                  , 'FFFF', 'FFFF', 'spyro/silver-eruptor.jpg', [Tag.Silver])
    Chop_Chop_Gold                 = ('Chop Chop Gold'              , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Chop_Chop                , 'FFFF', 'FFFF', 'spyro/chop-chop-gold.jpg', [Tag.Gold])
    Legendary_Trigger_Happy        = ('Legendary Trigger Happy'     , Game.Spyro_Adventure  , Element.Tech   , Character.Trigger_Happy            , 'a301', '0000', 'spyro/legendary-trigger-happy.jpg', [Tag.Legendary])
    Clear_Wham_Shell               = ('Clear Wham Shell'            , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Wham_Shell               , 'FFFF', 'FFFF', 'spyro/clear-wham-shell.jpg', [Tag.Clear])
    Metallic_Cynder                = ('Metallic Cynder'             , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Cynder                   , 'FFFF', 'FFFF', 'spyro/metallic-cynder.jpg', [Tag.Metallic])
    Clear_Whirlwind                = ('Clear Whirlwind'             , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Whirlwind                , 'FFFF', 'FFFF', 'spyro/clear-whirlwind.jpg', [Tag.Clear])
    Pearl_Hex                      = ('Pearl Hex'                   , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Hex                      , 'FFFF', 'FFFF', 'spyro/pearl-hex.jpg'    , [Tag.Pearl])
    Ignitor                        = ('Ignitor'                     , Game.Spyro_Adventure  , Element.Fire   , Character.Ignitor                  , '0a00', '0000', 'spyro/ignitor.jpg'      , [])
    Voodood                        = ('Voodood'                     , Game.Spyro_Adventure  , Element.Magic  , Character.Voodood                  , '1100', '0000', 'spyro/voodood.jpg'      , [])
    Gill_Grunt                     = ('Gill Grunt'                  , Game.Spyro_Adventure  , Element.Water  , Character.Gill_Grunt               , '0e00', '0000', 'spyro/gill-grunt.jpg'   , [])
    Warnado_Glow_In_Dark           = ('Warnado Glow In Dark'        , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Warnado                  , 'FFFF', 'FFFF', 'spyro/warnado-glow-in-dark.jpg', [Tag.Glow_In_Dark ,Tag.Dark])
    Drill_Sergeant                 = ('Drill Sergeant'              , Game.Spyro_Adventure  , Element.Tech   , Character.Drill_Sergeant           , '1500', '0000', 'spyro/drill-sergeant.jpg', [])
    Dark_Spyro                     = ('Dark Spyro'                  , Game.Spyro_Adventure  , Element.Magic  , Character.Spyro                    , '1000', '022c', 'spyro/dark-spyro.jpg'   , [Tag.Dark])
    Red_Camo_Skylander             = ('Red Camo Skylander'          , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Camo                     , 'FFFF', 'FFFF', 'spyro/red-camo-skylander.jpg', [Tag.Red])
    Whisper_Elf                    = ('Whisper Elf'                 , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Whisper_Elf              , 'FFFF', 'FFFF', 'spyro/whisper-elf.jpg'  , [])
    Drill_Sergeant_Red             = ('Drill Sergeant Red'          , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Drill_Sergeant           , 'FFFF', 'FFFF', 'spyro/drill-sergeant-red.jpg', [Tag.Red])
    Zap                            = ('Zap'                         , Game.Spyro_Adventure  , Element.Water  , Character.Zap                      , '0c00', '0000', 'spyro/zap.jpg'          , [])
    Silver_Boomer                  = ('Silver Boomer'               , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Boomer                   , 'FFFF', 'FFFF', 'spyro/silver-boomer.jpg', [Tag.Silver])
    Trigger_Happy                  = ('Trigger Happy'               , Game.Spyro_Adventure  , Element.Tech   , Character.Trigger_Happy            , '1300', '0000', 'spyro/trigger-happy.jpg', [])
    Ghost_Roaster                  = ('Ghost Roaster'               , Game.Spyro_Adventure  , Element.Undead , Character.Ghost_Roaster            , '1f00', '0000', 'spyro/ghost-roaster.jpg', [])
    Wrecking_Ball_Glow_In_Dark     = ('Wrecking Ball Glow In Dark'  , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Wrecking_Ball            , 'FFFF', 'FFFF', 'spyro/wrecking-ball-glow-in-dark.jpg', [Tag.Glow_In_Dark ,Tag.Dark])
    Zap_Glow_In_Dark               = ('Zap Glow In Dark'            , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Zap                      , 'FFFF', 'FFFF', 'spyro/zap-glow-in-dark.jpg', [Tag.Glow_In_Dark ,Tag.Dark])
    Eruptor                        = ('Eruptor'                     , Game.Spyro_Adventure  , Element.Fire   , Character.Eruptor                  , '0900', '0000', 'spyro/eruptor.jpg'      , [])
    Terrafin                       = ('Terrafin'                    , Game.Spyro_Adventure  , Element.Earth  , Character.Terrafin                 , '0500', '0000', 'spyro/terrafin.jpg'     , [])
    Flameslinger_Series_1_Gold     = ('Flameslinger Series 1 Gold'  , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Flameslinger             , 'FFFF', 'FFFF', 'spyro/flameslinger-series-1-gold.jpg', [Tag.Gold])
    Legendary_Chop_Chop            = ('Legendary Chop Chop'         , Game.Spyro_Adventure  , Element.Undead , Character.Chop_Chop                , 'ae01', '0000', 'spyro/legendary-chop-chop.jpg', [Tag.Legendary])
    Clear_Stealth_Elf              = ('Clear Stealth Elf'           , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Stealth_Elf              , 'FFFF', 'FFFF', 'spyro/clear-stealth-elf.jpg', [Tag.Clear])
    Flameslinger                   = ('Flameslinger'                , Game.Spyro_Adventure  , Element.Fire   , Character.Flameslinger             , '0b00', '0000', 'spyro/flameslinger.jpg' , [])
    Slam_Bam                       = ('Slam Bam'                    , Game.Spyro_Adventure  , Element.Water  , Character.Slam_Bam                 , '0f00', '0000', 'spyro/slam-bam.jpg'     , [])
    Zook                           = ('Zook'                        , Game.Spyro_Adventure  , Element.Life   , Character.Zook                     , '1900', '0000', 'spyro/zook.jpg'         , [])
    Stealth_Elf                    = ('Stealth Elf'                 , Game.Spyro_Adventure  , Element.Life   , Character.Stealth_Elf              , '1a00', '0000', 'spyro/stealth-elf.jpg'  , [])
    Legendary_Bash                 = ('Legendary Bash'              , Game.Spyro_Adventure  , Element.Earth  , Character.Bash                     , '9401', '0000', 'spyro/legendary-bash.jpg', [Tag.Legendary])
    Legendary_Spyro                = ('Legendary Spyro'             , Game.Spyro_Adventure  , Element.Magic  , Character.Spyro                    , 'a001', '0000', 'spyro/legendary-spyro.jpg', [Tag.Legendary])
    Sonic_Boom                     = ('Sonic Boom'                  , Game.Spyro_Adventure  , Element.Air    , Character.Sonic_Boom               , '0100', '0000', 'spyro/sonic-boom.jpg'   , [])
    Prism_Break                    = ('Prism Break'                 , Game.Spyro_Adventure  , Element.Earth  , Character.Prism_Break              , '0700', '0000', 'spyro/prism-break.jpg'  , [])
    Cynder                         = ('Cynder'                      , Game.Spyro_Adventure  , Element.Undead , Character.Cynder                   , '2000', '0000', 'spyro/cynder.jpg'       , [])
    Bash                           = ('Bash'                        , Game.Spyro_Adventure  , Element.Earth  , Character.Bash                     , '0400', '0000', 'spyro/bash.jpg'         , [])
    Warnado                        = ('Warnado'                     , Game.Spyro_Adventure  , Element.Air    , Character.Warnado                  , '0200', '0000', 'spyro/warnado.jpg'      , [])
    Wrecking_Ball                  = ('Wrecking Ball'               , Game.Spyro_Adventure  , Element.Magic  , Character.Wrecking_Ball            , '1700', '0000', 'spyro/wrecking-ball.jpg', [])
    Sunburn                        = ('Sunburn'                     , Game.Spyro_Adventure  , Element.Fire   , Character.Sunburn                  , '0800', '0000', 'spyro/sunburn.jpg'      , [])
    Blue_Bash                      = ('Blue Bash'                   , Game.Spyro_Adventure  , Element.Earth  , Character.Bash                     , '0400', '0000', 'spyro/blue-bash.jpg'    , [Tag.Blue])
    Chop_Chop                      = ('Chop Chop'                   , Game.Spyro_Adventure  , Element.Undead , Character.Chop_Chop                , '1e00', '0000', 'spyro/chop-chop.jpg'    , [])
    Clear_Cynder                   = ('Clear Cynder'                , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Cynder                   , 'FFFF', 'FFFF', 'spyro/clear-cynder.jpg' , [Tag.Clear])
    Double_Trouble_Royal           = ('Double Trouble Royal'        , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Double_Trouble           , 'FFFF', 'FFFF', 'spyro/double-trouble-royal.jpg', [Tag.Royal])
    Stump_Smash_Flocked            = ('Stump Smash Flocked'         , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Stump_Smash              , 'FFFF', 'FFFF', 'spyro/stump-smash-flocked.jpg', [Tag.Flocked])
    Gill_Runt_Sidekick             = ('Gill Runt Sidekick'          , Game.Spyro_Adventure  , Element.UNKNOWN, Character.Gill_Runt                , 'FFFF', 'FFFF', 'spyro/gill-runt-sidekick.jpg', [Tag.Sidekick])
    Whirlwind                      = ('Whirlwind'                   , Game.Spyro_Adventure  , Element.Air    , Character.Whirlwind                , '0000', '0000', 'spyro/whirlwind.jpg'    , [])
    Bash_Series_2                  = ('Bash Series 2'               , Game.Giants           , Element.UNKNOWN, Character.Bash                     , 'FFFF', 'FFFF', 'giants/bash-series-2.jpg', [])
    Chill                          = ('Chill'                       , Game.Giants           , Element.Water  , Character.Chill                    , '6a00', '0010', 'giants/chill.jpg'       , [])
    Prism_Break_Lightcore_Flocked  = ('Prism Break Lightcore Flocked', Game.Giants           , Element.UNKNOWN, Character.Prism_Break              , 'FFFF', 'FFFF', 'giants/prism-break-lightcore-flocked.jpg', [Tag.Flocked])
    Prism_Break_Series_2           = ('Prism Break Series 2'        , Game.Giants           , Element.UNKNOWN, Character.Prism_Break              , 'FFFF', 'FFFF', 'giants/prism-break-series-2.jpg', [])
    Sprocket_Sparkle               = ('Sprocket Sparkle'            , Game.Giants           , Element.UNKNOWN, Character.Sprocket                 , 'FFFF', 'FFFF', 'giants/sprocket-sparkle.jpg', [Tag.Sparkle])
    Terrafin_Series_2              = ('Terrafin Series 2'           , Game.Giants           , Element.UNKNOWN, Character.Terrafin                 , 'FFFF', 'FFFF', 'giants/terrafin-series-2.jpg', [])
    Wrecking_Ball_Series_2         = ('Wrecking Ball Series 2'      , Game.Giants           , Element.UNKNOWN, Character.Wrecking_Ball            , 'FFFF', 'FFFF', 'giants/wrecking-ball-series-2.jpg', [])
    Sonic_Boom_Series_2            = ('Sonic Boom Series 2'         , Game.Giants           , Element.UNKNOWN, Character.Sonic_Boom               , 'FFFF', 'FFFF', 'giants/sonic-boom-series-2.jpg', [])
    Eye_Brawl                      = ('Eye Brawl'                   , Game.Giants           , Element.Undead , Character.Eye_Brawl                , '7200', '0612', 'giants/eye-brawl.jpg'   , [])
    Sprocket                       = ('Sprocket'                    , Game.Giants           , Element.Tech   , Character.Sprocket                 , '6f00', '0010', 'giants/sprocket.jpg'    , [])
    Stealth_Elf_Series_2_Legendary = ('Stealth Elf Series 2 Legendary', Game.Giants           , Element.UNKNOWN, Character.Stealth_Elf              , 'FFFF', 'FFFF', 'giants/stealth-elf-series-2-legendary.jpg', [Tag.Legendary])
    Prism_Break_2012_Gift          = ('Prism Break 2012 Gift'       , Game.Giants           , Element.UNKNOWN, Character.Prism_Break_2012_Gift    , 'FFFF', 'FFFF', 'giants/prism-break-2012-gift.jpg', [])
    Lightning_Rod_Series_2         = ('Lightning Rod Series 2'      , Game.Giants           , Element.UNKNOWN, Character.Lightning_Rod            , 'FFFF', 'FFFF', 'giants/lightning-rod-series-2.jpg', [])
    Zook_Series_2                  = ('Zook Series 2'               , Game.Giants           , Element.UNKNOWN, Character.Zook                     , 'FFFF', 'FFFF', 'giants/zook-series-2.jpg', [])
    Mini_Jini_Sidekick             = ('Mini Jini Sidekick'          , Game.Giants           , Element.UNKNOWN, Character.Jini                     , 'FFFF', 'FFFF', 'giants/mini-jini-sidekick.jpg', [Tag.Mini ,Tag.Sidekick])
    Punch_Pop_Fizz                 = ('Punch Pop Fizz'              , Game.Giants           , Element.Magic  , Character.Pop_Fizz                 , '6c00', '0214', 'giants/punch-pop-fizz.jpg', [Tag.Punch])
    Cynder_Series_2_Glowindark     = ('Cynder Series 2 Glowindark'  , Game.Giants           , Element.UNKNOWN, Character.Cynder                   , 'FFFF', 'FFFF', 'giants/cynder-series-2-glowindark.jpg', [Tag.Glowindark])
    Legendary_Ignitor              = ('Legendary Ignitor'           , Game.Giants           , Element.Fire   , Character.Ignitor                  , '0a00', '031c', 'giants/legendary-ignitor.jpg', [Tag.Legendary])
    Whirlwind_Series_2_Stone       = ('Whirlwind Series 2 Stone'    , Game.Giants           , Element.UNKNOWN, Character.Whirlwind                , 'FFFF', 'FFFF', 'giants/whirlwind-series-2-stone.jpg', [Tag.Stone])
    Sonic_Boom_Glitter             = ('Sonic Boom Glitter'          , Game.Giants           , Element.UNKNOWN, Character.Sonic_Boom               , 'FFFF', 'FFFF', 'giants/sonic-boom-glitter.jpg', [Tag.Glitter])
    Legendary_Slam_Bam             = ('Legendary Slam Bam'          , Game.Giants           , Element.Water  , Character.Slam_Bam                 , '0f00', '031c', 'giants/legendary-slam-bam.jpg', [Tag.Legendary])
    Flashwing                      = ('Flashwing'                   , Game.Giants           , Element.Earth  , Character.Flashwing                , '6700', '0010', 'giants/flashwing.jpg'   , [])
    Drill_Sergeant_Series_2        = ('Drill Sergeant Series 2'     , Game.Giants           , Element.UNKNOWN, Character.Drill_Sergeant           , 'FFFF', 'FFFF', 'giants/drill-sergeant-series-2.jpg', [])
    Hot_Dog_Color_Shift            = ('Hot Dog Color Shift'         , Game.Giants           , Element.UNKNOWN, Character.Hot_Dog                  , 'FFFF', 'FFFF', 'giants/hot-dog-color-shift.jpg', [Tag.Color_Shift])
    Pop_Fizz                       = ('Pop Fizz'                    , Game.Giants           , Element.Magic  , Character.Pop_Fizz                 , '6c00', '0010', 'giants/pop-fizz.jpg'    , [])
    Eye_Small_Sidekick             = ('Eye Small Sidekick'          , Game.Giants           , Element.UNKNOWN, Character.Eye_Small                , 'FFFF', 'FFFF', 'giants/eye-small-sidekick.jpg', [Tag.Sidekick])
    Chill_Lightcore                = ('Chill Lightcore'             , Game.Giants           , Element.UNKNOWN, Character.Chill                    , 'FFFF', 'FFFF', 'giants/chill-lightcore.jpg', [Tag.Lightcore])
    Shroomboom                     = ('Shroomboom'                  , Game.Giants           , Element.Life   , Character.Shroomboom               , '7100', '0010', 'giants/shroomboom.jpg'  , [])
    Pumpkin_Eye_Brawl              = ('Pumpkin Eye Brawl'           , Game.Giants           , Element.UNKNOWN, Character.Pumpkin_Eye_Brawl        , 'FFFF', 'FFFF', 'giants/pumpkin-eye-brawl.jpg', [])
    Metallic_Shroomboom            = ('Metallic Shroomboom'         , Game.Giants           , Element.UNKNOWN, Character.Shroomboom               , 'FFFF', 'FFFF', 'giants/metallic-shroomboom.jpg', [Tag.Metallic])
    Fright_Rider_Glowindark        = ('Fright Rider Glowindark'     , Game.Giants           , Element.UNKNOWN, Character.Fright_Rider             , 'FFFF', 'FFFF', 'giants/fright-rider-glowindark.jpg', [Tag.Glowindark])
    Prism_Break_Lightcore          = ('Prism Break Lightcore'       , Game.Giants           , Element.UNKNOWN, Character.Prism_Break              , 'FFFF', 'FFFF', 'giants/prism-break-lightcore.jpg', [Tag.Lightcore])
    Tree_Rex                       = ('Tree Rex'                    , Game.Giants           , Element.Life   , Character.Tree_Rex                 , '7000', '0612', 'giants/tree-rex.jpg'    , [])
    Hot_Head                       = ('Hot Head'                    , Game.Giants           , Element.Fire   , Character.Hot_Head                 , '6800', '0612', 'giants/hot-head.jpg'    , [])
    Legendary_Bouncer              = ('Legendary Bouncer'           , Game.Giants           , Element.Tech   , Character.Bouncer                  , '6e00', '0316', 'giants/legendary-bouncer.jpg', [Tag.Legendary])
    Gnarly_Tree_Rex                = ('Gnarly Tree Rex'             , Game.Giants           , Element.Life   , Character.Gnarly_Tree_Rex          , '7000', '0216', 'giants/gnarly-tree-rex.jpg', [])
    Ninjini                        = ('Ninjini'                     , Game.Giants           , Element.Magic  , Character.Ninjini                  , '6d00', '0612', 'giants/ninjini.jpg'     , [])
    Hex_Lightcore                  = ('Hex Lightcore'               , Game.Giants           , Element.UNKNOWN, Character.Hex                      , 'FFFF', 'FFFF', 'giants/hex-lightcore.jpg', [Tag.Lightcore])
    Drobot_Series_2                = ('Drobot Series 2'             , Game.Giants           , Element.UNKNOWN, Character.Drobot                   , 'FFFF', 'FFFF', 'giants/drobot-series-2.jpg', [])
    Halloween_Fright_Rider         = ('Halloween Fright Rider'      , Game.Giants           , Element.UNKNOWN, Character.Halloween_Fright_Rider   , 'FFFF', 'FFFF', 'giants/halloween-fright-rider.jpg', [])
    Metallic_Green_Gill_Grunt      = ('Metallic Green Gill Grunt'   , Game.Giants           , Element.UNKNOWN, Character.Gill_Grunt               , 'FFFF', 'FFFF', 'giants/metallic-green-gill-grunt.jpg', [Tag.Metallic])
    Ninjini_Scarlet                = ('Ninjini Scarlet'             , Game.Giants           , Element.UNKNOWN, Character.Ninjini_Scarlet          , 'FFFF', 'FFFF', 'giants/ninjini-scarlet.jpg', [])
    Hot_Head_Sparkle               = ('Hot Head Sparkle'            , Game.Giants           , Element.UNKNOWN, Character.Hot_Head                 , 'FFFF', 'FFFF', 'giants/hot-head-sparkle.jpg', [Tag.Sparkle])
    Jet_Vac                        = ('Jet Vac'                     , Game.Giants           , Element.Air    , Character.Jet_Vac                  , '6400', '0010', 'giants/jet-vac.jpg'     , [])
    Spyro_Series_2                 = ('Spyro Series 2'              , Game.Giants           , Element.UNKNOWN, Character.Spyro                    , 'FFFF', 'FFFF', 'giants/spyro-series-2.jpg', [])
    Purple_Eye_Brawl               = ('Purple Eye Brawl'            , Game.Giants           , Element.UNKNOWN, Character.Eye_Brawl                , 'FFFF', 'FFFF', 'giants/purple-eye-brawl.jpg', [Tag.Purple])
    Double_Trouble_Series_2        = ('Double Trouble Series 2'     , Game.Giants           , Element.UNKNOWN, Character.Double_Trouble           , 'FFFF', 'FFFF', 'giants/double-trouble-series-2.jpg', [])
    Pop_Fizz_Lightcore             = ('Pop Fizz Lightcore'          , Game.Giants           , Element.UNKNOWN, Character.Pop_Fizz                 , 'FFFF', 'FFFF', 'giants/pop-fizz-lightcore.jpg', [Tag.Lightcore])
    Chop_Chop_Series_2             = ('Chop Chop Series 2'          , Game.Giants           , Element.UNKNOWN, Character.Chop_Chop                , 'FFFF', 'FFFF', 'giants/chop-chop-series-2.jpg', [])
    Granite_Crusher                = ('Granite Crusher'             , Game.Giants           , Element.Earth  , Character.Granite_Crusher          , '6600', '0216', 'giants/granite-crusher.jpg', [])
    Legendary_Jet_Vac              = ('Legendary Jet Vac'           , Game.Giants           , Element.Air    , Character.Jet_Vac                  , '6400', '0314', 'giants/legendary-jet-vac.jpg', [Tag.Legendary])
    Flameslinger_Series2_Gold      = ('Flameslinger Series2 Gold'   , Game.Giants           , Element.UNKNOWN, Character.Flameslinger             , 'FFFF', 'FFFF', 'giants/flameslinger-series2-gold.jpg', [Tag.Gold])
    Bouncer                        = ('Bouncer'                     , Game.Giants           , Element.Tech   , Character.Bouncer                  , '6e00', '0612', 'giants/bouncer.jpg'     , [])
    Sonic_Boom_Glowindark          = ('Sonic Boom Glowindark'       , Game.Giants           , Element.UNKNOWN, Character.Sonic_Boom               , 'FFFF', 'FFFF', 'giants/sonic-boom-glowindark.jpg', [Tag.Glowindark])
    Fright_Rider                   = ('Fright Rider'                , Game.Giants           , Element.Undead , Character.Fright_Rider             , '7300', '0010', 'giants/fright-rider.jpg', [])
    Flashwing_Jade                 = ('Flashwing Jade'              , Game.Giants           , Element.UNKNOWN, Character.Flashwing                , 'FFFF', 'FFFF', 'giants/flashwing-jade.jpg', [Tag.Jade])
    Slam_Bam_Series_2              = ('Slam Bam Series 2'           , Game.Giants           , Element.UNKNOWN, Character.Slam_Bam                 , 'FFFF', 'FFFF', 'giants/slam-bam-series-2.jpg', [])
    Drobot_Lightcore               = ('Drobot Lightcore'            , Game.Giants           , Element.UNKNOWN, Character.Drobot                   , 'FFFF', 'FFFF', 'giants/drobot-lightcore.jpg', [Tag.Lightcore])
    Jet_Vac_Lightcore              = ('Jet Vac Lightcore'           , Game.Giants           , Element.UNKNOWN, Character.Jet_Vac                  , 'FFFF', 'FFFF', 'giants/jet-vac-lightcore.jpg', [Tag.Lightcore])
    Swarm                          = ('Swarm'                       , Game.Giants           , Element.Air    , Character.Swarm                    , '6500', '0612', 'giants/swarm.jpg'       , [])
    Eruptor_Lightcore              = ('Eruptor Lightcore'           , Game.Giants           , Element.UNKNOWN, Character.Eruptor                  , 'FFFF', 'FFFF', 'giants/eruptor-lightcore.jpg', [Tag.Lightcore])
    Chop_Chop_Toy_Fair             = ('Chop Chop Toy Fair'          , Game.Giants           , Element.UNKNOWN, Character.Chop_Chop                , 'FFFF', 'FFFF', 'giants/chop-chop-toy-fair.jpg', [Tag.Toy_Fair])
    Purple_Wrecking_Ball           = ('Purple Wrecking Ball'        , Game.Giants           , Element.UNKNOWN, Character.Wrecking_Ball            , 'FFFF', 'FFFF', 'giants/purple-wrecking-ball.jpg', [Tag.Purple])
    Barkley                        = ('Barkley'                     , Game.Giants           , Element.UNKNOWN, Character.Barkley                  , 'FFFF', 'FFFF', 'giants/barkley.jpg'     , [])
    Ignitor_Series_2               = ('Ignitor Series 2'            , Game.Giants           , Element.UNKNOWN, Character.Ignitor                  , 'FFFF', 'FFFF', 'giants/ignitor-series-2.jpg', [])
    Hot_Dog_Molten                 = ('Hot Dog Molten'              , Game.Giants           , Element.UNKNOWN, Character.Hot_Dog                  , 'FFFF', 'FFFF', 'giants/hot-dog-molten.jpg', [Tag.Molten])
    Flameslinger_Series_2          = ('Flameslinger Series 2'       , Game.Giants           , Element.UNKNOWN, Character.Flameslinger             , 'FFFF', 'FFFF', 'giants/flameslinger-series-2.jpg', [])
    Trigger_Happy_Series_2         = ('Trigger Happy Series 2'      , Game.Giants           , Element.UNKNOWN, Character.Trigger_Happy            , 'FFFF', 'FFFF', 'giants/trigger-happy-series-2.jpg', [])
    Stealth_Elf_Series_2           = ('Stealth Elf Series 2'        , Game.Giants           , Element.UNKNOWN, Character.Stealth_Elf              , 'FFFF', 'FFFF', 'giants/stealth-elf-series-2.jpg', [])
    Zap_Series_2                   = ('Zap Series 2'                , Game.Giants           , Element.UNKNOWN, Character.Zap                      , 'FFFF', 'FFFF', 'giants/zap-series-2.jpg', [])
    Gill_Grunt_Series_2            = ('Gill Grunt Series 2'         , Game.Giants           , Element.UNKNOWN, Character.Gill_Grunt               , 'FFFF', 'FFFF', 'giants/gill-grunt-series-2.jpg', [])
    Chill_Legendary                = ('Chill Legendary'             , Game.Giants           , Element.UNKNOWN, Character.Chill                    , 'FFFF', 'FFFF', 'giants/chill-legendary.jpg', [Tag.Legendary])
    Eruptor_Series_2_Flocked       = ('Eruptor Series 2 Flocked'    , Game.Giants           , Element.UNKNOWN, Character.Eruptor                  , 'FFFF', 'FFFF', 'giants/eruptor-series-2-flocked.jpg', [Tag.Flocked])
    Stump_Smash_Series_2_Flocked   = ('Stump Smash Series 2 Flocked', Game.Giants           , Element.UNKNOWN, Character.Stump_Smash              , 'FFFF', 'FFFF', 'giants/stump-smash-series-2-flocked.jpg', [Tag.Flocked])
    Zook_Series_2_Stone            = ('Zook Series 2 Stone'         , Game.Giants           , Element.UNKNOWN, Character.Zook                     , 'FFFF', 'FFFF', 'giants/zook-series-2-stone.jpg', [Tag.Stone])
    Whirlwind_Polar                = ('Whirlwind Polar'             , Game.Giants           , Element.UNKNOWN, Character.Whirlwind                , 'FFFF', 'FFFF', 'giants/whirlwind-polar.jpg', [Tag.Polar])
    Hot_Dog                        = ('Hot Dog'                     , Game.Giants           , Element.Fire   , Character.Hot_Dog                  , '6900', '0010', 'giants/hot-dog.jpg'     , [])
    Crusher                        = ('Crusher'                     , Game.Giants           , Element.Earth  , Character.Crusher                  , '6600', '0612', 'giants/crusher.jpg'     , [])
    Shroomboom_Lightcore           = ('Shroomboom Lightcore'        , Game.Giants           , Element.UNKNOWN, Character.Shroomboom               , 'FFFF', 'FFFF', 'giants/shroomboom-lightcore.jpg', [Tag.Lightcore])
    Hex_Series_2                   = ('Hex Series 2'                , Game.Giants           , Element.UNKNOWN, Character.Hex                      , 'FFFF', 'FFFF', 'giants/hex-series-2.jpg', [])
    Stump_Smash_Series_2           = ('Stump Smash Series 2'        , Game.Giants           , Element.UNKNOWN, Character.Stump_Smash              , 'FFFF', 'FFFF', 'giants/stump-smash-series-2.jpg', [])
    Thumpback                      = ('Thumpback'                   , Game.Giants           , Element.Water  , Character.Thumpback                , '6b00', '0612', 'giants/thumpback.jpg'   , [])
    Thumpling                      = ('Thumpling'                   , Game.Giants           , Element.UNKNOWN, Character.Thumpling                , 'FFFF', 'FFFF', 'giants/thumpling.jpg'   , [])
    Cynder_Series_2                = ('Cynder Series 2'             , Game.Giants           , Element.UNKNOWN, Character.Cynder                   , 'FFFF', 'FFFF', 'giants/cynder-series-2.jpg', [])
    Eruptor_Series_2               = ('Eruptor Series 2'            , Game.Giants           , Element.UNKNOWN, Character.Eruptor                  , 'FFFF', 'FFFF', 'giants/eruptor-series-2.jpg', [])
    Whirlwind_Series_2             = ('Whirlwind Series 2'          , Game.Giants           , Element.UNKNOWN, Character.Whirlwind                , 'FFFF', 'FFFF', 'giants/whirlwind-series-2.jpg', [])
    Lightning_Rod_Violet_Metallic  = ('Lightning Rod Violet Metallic', Game.Giants           , Element.UNKNOWN, Character.Lightning_Rod            , 'FFFF', 'FFFF', 'giants/lightning-rod-violet-metallic.jpg', [Tag.Metallic])
    Zoo_Lou                        = ('Zoo Lou'                     , Game.Swap_Force       , Element.Life   , Character.Zoo_Lou                  , 'bf0b', '0020', 'swap-force/zoo-lou.jpg' , [])
    Doom_Stone                     = ('Doom Stone'                  , Game.Swap_Force       , Element.Earth  , Character.Doom                     , 'eb03', '0020', 'swap-force/doom-stone.jpg', [Tag.Stone])
    Legendary_Night_Shift          = ('Legendary Night Shift'       , Game.Swap_Force       , Element.Undead , Character.Night_Shift              , 'f403', '0324', 'swap-force/legendary-night-shift.jpg', [Tag.Legendary])
    Enchanted_Hoot_Loop            = ('Enchanted Hoot Loop'         , Game.Swap_Force       , Element.Magic  , Character.Hoot_Loop                , 'f003', '0224', 'swap-force/enchanted-hoot-loop.jpg', [Tag.Enchanted])
    Prism_Break_Series_3           = ('Prism Break Series 3'        , Game.Swap_Force       , Element.UNKNOWN, Character.Prism_Break              , 'FFFF', 'FFFF', 'swap-force/prism-break-series-3.jpg', [])
    Jade_Fire_Kraken               = ('Jade Fire Kraken'            , Game.Swap_Force       , Element.Fire   , Character.Fire_Kraken              , 'ed03', '0224', 'swap-force/jade-fire-kraken.jpg', [Tag.Jade])
    Trigger_Happy_Series_3         = ('Trigger Happy Series 3'      , Game.Swap_Force       , Element.UNKNOWN, Character.Trigger_Happy            , 'FFFF', 'FFFF', 'swap-force/trigger-happy-series-3.jpg', [])
    Lightcore_Bumble_Blast         = ('Lightcore Bumble Blast'      , Game.Swap_Force       , Element.Life   , Character.Bumble_Blast             , 'be0b', '0622', 'swap-force/lightcore-bumble-blast.jpg', [Tag.Lightcore])
    Night_Shift                    = ('Night Shift'                 , Game.Swap_Force       , Element.Undead , Character.Night_Shift              , 'f403', '0020', 'swap-force/night-shift.jpg', [])
    Spyro_Series_3_Dark            = ('Spyro Series 3 Dark'         , Game.Swap_Force       , Element.UNKNOWN, Character.Spyro                    , 'FFFF', 'FFFF', 'swap-force/spyro-series-3-dark.jpg', [Tag.Dark])
    Slobber_Tooth_Dark             = ('Slobber Tooth Dark'          , Game.Swap_Force       , Element.UNKNOWN, Character.Slobber_Tooth            , 'FFFF', 'FFFF', 'swap-force/slobber-tooth-dark.jpg', [Tag.Dark])
    Hoot_Loop                      = ('Hoot Loop'                   , Game.Swap_Force       , Element.Magic  , Character.Hoot_Loop                , 'f003', '0020', 'swap-force/hoot-loop.jpg', [])
    Eruptor_Volcanic_Lava_Barf     = ('Eruptor Volcanic Lava Barf'  , Game.Swap_Force       , Element.UNKNOWN, Character.Eruptor_Volcanic_Lava_Barf, 'FFFF', 'FFFF', 'swap-force/eruptor-volcanic-lava-barf.jpg', [])
    Star_Strike                    = ('Star Strike'                 , Game.Swap_Force       , Element.Magic  , Character.Star_Strike              , 'c10b', '0020', 'swap-force/star-strike.jpg', [])
    Dune_Bug                       = ('Dune Bug'                    , Game.Swap_Force       , Element.Magic  , Character.Dune_Bug                 , 'c00b', '0020', 'swap-force/dune-bug.jpg', [])
    Metallic_Heavy_Duty_Sprocket   = ('Metallic Heavy Duty Sprocket', Game.Swap_Force       , Element.UNKNOWN, Character.Sprocket                 , 'FFFF', 'FFFF', 'swap-force/metallic-heavy-duty-sprocket.jpg', [Tag.Metallic])
    Trap_Shadow                    = ('Trap Shadow'                 , Game.Swap_Force       , Element.Magic  , Character.Trap_Shadow              , 'f103', '0020', 'swap-force/trap-shadow.jpg', [])
    Grim_Creeper_Legendary         = ('Grim Creeper Legendary'      , Game.Swap_Force       , Element.UNKNOWN, Character.Grim_Creeper             , 'FFFF', 'FFFF', 'swap-force/grim-creeper-legendary.jpg', [Tag.Legendary])
    Boom_Jet                       = ('Boom Jet'                    , Game.Swap_Force       , Element.Air    , Character.Boom_Jet                 , 'e803', '0020', 'swap-force/boom-jet.jpg', [])
    Chill_Series_2                 = ('Chill Series 2'              , Game.Swap_Force       , Element.UNKNOWN, Character.Chill                    , 'FFFF', 'FFFF', 'swap-force/chill-series-2.jpg', [])
    Whirlwind_Series_3             = ('Whirlwind Series 3'          , Game.Swap_Force       , Element.UNKNOWN, Character.Whirlwind                , 'FFFF', 'FFFF', 'swap-force/whirlwind-series-3.jpg', [])
    Pop_Fizz_Series_2              = ('Pop Fizz Series 2'           , Game.Swap_Force       , Element.UNKNOWN, Character.Pop_Fizz                 , 'FFFF', 'FFFF', 'swap-force/pop-fizz-series-2.jpg', [])
    Rattle_Shake_Quickdraw         = ('Rattle Shake Quickdraw'      , Game.Swap_Force       , Element.UNKNOWN, Character.Rattle_Shake             , 'FFFF', 'FFFF', 'swap-force/rattle-shake-quickdraw.jpg', [Tag.Quickdraw])
    Smolderdash_Lightcore          = ('Smolderdash Lightcore'       , Game.Swap_Force       , Element.UNKNOWN, Character.Smolderdash              , 'FFFF', 'FFFF', 'swap-force/smolderdash-lightcore.jpg', [Tag.Lightcore])
    Lightcore_Countdown            = ('Lightcore Countdown'         , Game.Swap_Force       , Element.Tech   , Character.Countdown                , 'c20b', '0622', 'swap-force/lightcore-countdown.jpg', [Tag.Lightcore])
    Countdown                      = ('Countdown'                   , Game.Swap_Force       , Element.Tech   , Character.Countdown                , 'c20b', '0020', 'swap-force/countdown.jpg', [])
    Gill_Grunt_Series_3            = ('Gill Grunt Series 3'         , Game.Swap_Force       , Element.UNKNOWN, Character.Gill_Grunt               , 'FFFF', 'FFFF', 'swap-force/gill-grunt-series-3.jpg', [])
    Silver_Gold_Stink_Bomb         = ('Silver Gold Stink Bomb'      , Game.Swap_Force       , Element.UNKNOWN, Character.Gold_Stink_Bomb          , 'FFFF', 'FFFF', 'swap-force/silver-gold-stink-bomb.jpg', [Tag.Silver])
    Green_Armored_Riptide          = ('Green Armored Riptide'       , Game.Swap_Force       , Element.UNKNOWN, Character.Armored_Riptide          , 'FFFF', 'FFFF', 'swap-force/green-armored-riptide.jpg', [Tag.Green])
    Spy_Rise                       = ('Spy Rise'                    , Game.Swap_Force       , Element.Tech   , Character.Spy_Rise                 , 'f303', '0020', 'swap-force/spy-rise.jpg', [])
    Rollerbrawl                    = ('Rollerbrawl'                 , Game.Swap_Force       , Element.UNKNOWN, Character.Rollerbrawl              , 'FFFF', 'FFFF', 'swap-force/rollerbrawl.jpg', [])
    Wash_Buckler_Color_Shift       = ('Wash Buckler Color Shift'    , Game.Swap_Force       , Element.UNKNOWN, Character.Wash_Buckler             , 'FFFF', 'FFFF', 'swap-force/wash-buckler-color-shift.jpg', [Tag.Color_Shift])
    Bumble_Blast                   = ('Bumble Blast'                , Game.Swap_Force       , Element.Life   , Character.Bumble_Blast             , 'be0b', '0020', 'swap-force/bumble-blast.jpg', [])
    Red_Flame_Fire_Bone_Hot_Dog    = ('Red Flame Fire Bone Hot Dog' , Game.Swap_Force       , Element.UNKNOWN, Character.Flame_Fire_Bone_Hot_Dog  , 'FFFF', 'FFFF', 'swap-force/red-flame-fire-bone-hot-dog.jpg', [Tag.Red])
    Grim_Creeper_Lightcore         = ('Grim Creeper Lightcore'      , Game.Swap_Force       , Element.UNKNOWN, Character.Grim_Creeper             , 'FFFF', 'FFFF', 'swap-force/grim-creeper-lightcore.jpg', [Tag.Lightcore])
    Hot_Dog_Series_2               = ('Hot Dog Series 2'            , Game.Swap_Force       , Element.UNKNOWN, Character.Hot_Dog                  , 'FFFF', 'FFFF', 'swap-force/hot-dog-series-2.jpg', [])
    Lightcore_Star_Strike          = ('Lightcore Star Strike'       , Game.Swap_Force       , Element.Magic  , Character.Star_Strike              , 'c10b', '0622', 'swap-force/lightcore-star-strike.jpg', [Tag.Lightcore])
    Spyro_Mega_Ram                 = ('Spyro Mega Ram'              , Game.Swap_Force       , Element.UNKNOWN, Character.Spyro                    , 'FFFF', 'FFFF', 'swap-force/spyro-mega-ram.jpg', [Tag.Mega_Ram])
    Enchanted_Star_Strike          = ('Enchanted Star Strike'       , Game.Swap_Force       , Element.UNKNOWN, Character.Star_Strike              , 'FFFF', 'FFFF', 'swap-force/enchanted-star-strike.jpg', [Tag.Enchanted])
    Gold_Fire_Kraken               = ('Gold Fire Kraken'            , Game.Swap_Force       , Element.UNKNOWN, Character.Fire_Kraken              , 'FFFF', 'FFFF', 'swap-force/gold-fire-kraken.jpg', [Tag.Gold])
    Grim_Creeper                   = ('Grim Creeper'                , Game.Swap_Force       , Element.Undead , Character.Grim_Creeper             , 'c50b', '0020', 'swap-force/grim-creeper.jpg', [])
    Fryno                          = ('Fryno'                       , Game.Swap_Force       , Element.Fire   , Character.Fryno                    , 'bc0b', '0020', 'swap-force/fryno.jpg'   , [])
    Stink_Bomb                     = ('Stink Bomb'                  , Game.Swap_Force       , Element.Life   , Character.Stink_Bomb               , 'ee03', '0020', 'swap-force/stink-bomb.jpg', [])
    Trap_Shadow_Silver_Bronze_Variant_Skylander = ('Trap Shadow Silver Bronze Variant Skylander', Game.Swap_Force       , Element.UNKNOWN, Character.Trap_Shadow              , 'FFFF', 'FFFF', 'swap-force/trap-shadow-silver-bronze-variant-skylander.jpg', [])
    Fire_Kraken                    = ('Fire Kraken'                 , Game.Swap_Force       , Element.Fire   , Character.Fire_Kraken              , 'ed03', '0020', 'swap-force/fire-kraken.jpg', [])
    Wash_Buckler                   = ('Wash Buckler'                , Game.Swap_Force       , Element.Water  , Character.Wash_Buckler             , 'f703', '0020', 'swap-force/wash-buckler.jpg', [])
    Wash_Buckler_Dark              = ('Wash Buckler Dark'           , Game.Swap_Force       , Element.UNKNOWN, Character.Wash_Buckler             , 'FFFF', 'FFFF', 'swap-force/wash-buckler-dark.jpg', [Tag.Dark])
    Chop_Chop_Series_3             = ('Chop Chop Series 3'          , Game.Swap_Force       , Element.UNKNOWN, Character.Chop_Chop                , 'FFFF', 'FFFF', 'swap-force/chop-chop-series-3.jpg', [])
    Springtime_Trigger_Happy       = ('Springtime Trigger Happy'    , Game.Swap_Force       , Element.Tech   , Character.Trigger_Happy            , '1300', '022c', 'swap-force/springtime-trigger-happy.jpg', [Tag.Springtime])
    Legendary_Zoo_Lou              = ('Legendary Zoo Lou'           , Game.Swap_Force       , Element.Life   , Character.Zoo_Lou                  , 'bf0b', '0324', 'swap-force/legendary-zoo-lou.jpg', [Tag.Legendary])
    Blast_Zone                     = ('Blast Zone'                  , Game.Swap_Force       , Element.Fire   , Character.Blast_Zone               , 'ec03', '0020', 'swap-force/blast-zone.jpg', [])
    Eruptor_Lava_Barf              = ('Eruptor Lava Barf'           , Game.Swap_Force       , Element.UNKNOWN, Character.Eruptor_Lava_Barf        , 'FFFF', 'FFFF', 'swap-force/eruptor-lava-barf.jpg', [])
    Freeze_Blade                   = ('Freeze Blade'                , Game.Swap_Force       , Element.Water  , Character.Freeze_Blade             , 'f603', '0020', 'swap-force/freeze-blade.jpg', [])
    Kickoff_Countdown              = ('Kickoff Countdown'           , Game.Swap_Force       , Element.Tech   , Character.Countdown                , 'c20b', '0224', 'swap-force/kickoff-countdown.jpg', [Tag.Kickoff])
    Purple_Flame_Fire_Bone_Hot_Dog = ('Purple Flame Fire Bone Hot Dog', Game.Swap_Force       , Element.UNKNOWN, Character.Flame_Fire_Bone_Hot_Dog  , 'FFFF', 'FFFF', 'swap-force/purple-flame-fire-bone-hot-dog.jpg', [Tag.Purple])
    Wind_Up                        = ('Wind Up'                     , Game.Swap_Force       , Element.Tech   , Character.Wind_Up                  , 'c30b', '0020', 'swap-force/wind-up.jpg' , [])
    Rattle_Shake                   = ('Rattle Shake'                , Game.Swap_Force       , Element.Undead , Character.Rattle_Shake             , 'f503', '0020', 'swap-force/rattle-shake.jpg', [])
    Grilla_Drilla                  = ('Grilla Drilla'               , Game.Swap_Force       , Element.Life   , Character.Grilla_Drilla            , 'ef03', '0020', 'swap-force/grilla-drilla.jpg', [])
    Nitro_Freeze_Blade             = ('Nitro Freeze Blade'          , Game.Swap_Force       , Element.Water  , Character.Freeze_Blade             , 'f603', '0224', 'swap-force/nitro-freeze-blade.jpg', [Tag.Nitro])
    Stealth_Elf_Swap_Force         = ('Stealth Elf Swap Force'      , Game.Swap_Force       , Element.UNKNOWN, Character.Stealth_Elf              , 'FFFF', 'FFFF', 'swap-force/stealth-elf-swap-force.jpg', [])
    Sprocket_Series_2              = ('Sprocket Series 2'           , Game.Swap_Force       , Element.UNKNOWN, Character.Sprocket                 , 'FFFF', 'FFFF', 'swap-force/sprocket-series-2.jpg', [])
    Green_Scorp                    = ('Green Scorp'                 , Game.Swap_Force       , Element.UNKNOWN, Character.Scorp                    , 'FFFF', 'FFFF', 'swap-force/green-scorp.jpg', [Tag.Green])
    Thorn_Horn_Camo                = ('Thorn Horn Camo'             , Game.Swap_Force       , Element.Life   , Character.Camo                     , '1800', '0528', 'swap-force/thorn-horn-camo.jpg', [Tag.Thorn_Horn])
    Blast_Zone_Dark                = ('Blast Zone Dark'             , Game.Swap_Force       , Element.UNKNOWN, Character.Blast_Zone               , 'FFFF', 'FFFF', 'swap-force/blast-zone-dark.jpg', [Tag.Dark])
    Riptide                        = ('Riptide'                     , Game.Swap_Force       , Element.UNKNOWN, Character.Riptide                  , 'FFFF', 'FFFF', 'swap-force/riptide.jpg' , [])
    Terrafin_Series_3              = ('Terrafin Series 3'           , Game.Swap_Force       , Element.UNKNOWN, Character.Terrafin                 , 'FFFF', 'FFFF', 'swap-force/terrafin-series-3.jpg', [])
    Red_Dune_Bug                   = ('Red Dune Bug'                , Game.Swap_Force       , Element.UNKNOWN, Character.Dune_Bug                 , 'FFFF', 'FFFF', 'swap-force/red-dune-bug.jpg', [Tag.Red])
    Free_Ranger                    = ('Free Ranger'                 , Game.Swap_Force       , Element.Air    , Character.Free_Ranger              , 'e903', '0020', 'swap-force/free-ranger.jpg', [])
    Rubble_Rouser                  = ('Rubble Rouser'               , Game.Swap_Force       , Element.Earth  , Character.Rubble_Rouser            , 'ea03', '0020', 'swap-force/rubble-rouser.jpg', [])
    Scratch                        = ('Scratch'                     , Game.Swap_Force       , Element.Air    , Character.Scratch                  , 'b80b', '0020', 'swap-force/scratch.jpg' , [])
    Magna_Charge                   = ('Magna Charge'                , Game.Swap_Force       , Element.Tech   , Character.Magna_Charge             , 'f203', '0020', 'swap-force/magna-charge.jpg', [])
    Nitro_Magna_Charge             = ('Nitro Magna Charge'          , Game.Swap_Force       , Element.Tech   , Character.Magna_Charge             , 'f203', '0224', 'swap-force/nitro-magna-charge.jpg', [Tag.Nitro])
    Stealth_Elf_Series_3_Dark      = ('Stealth Elf Series 3 Dark'   , Game.Swap_Force       , Element.UNKNOWN, Character.Stealth_Elf              , 'FFFF', 'FFFF', 'swap-force/stealth-elf-series-3-dark.jpg', [Tag.Dark])
    Fluffy_Springtime_Trigger_Happy = ('Fluffy Springtime Trigger Happy', Game.Swap_Force       , Element.UNKNOWN, Character.Trigger_Happy            , 'FFFF', 'FFFF', 'swap-force/fluffy-springtime-trigger-happy.jpg', [Tag.Fluffy])
    Legendary_Free_Ranger          = ('Legendary Free Ranger'       , Game.Swap_Force       , Element.Air    , Character.Free_Ranger              , 'e903', '0324', 'swap-force/legendary-free-ranger.jpg', [Tag.Legendary])
    Smolderdash                    = ('Smolderdash'                 , Game.Swap_Force       , Element.Fire   , Character.Smolderdash              , 'bd0b', '0020', 'swap-force/smolderdash.jpg', [])
    Wham_Shell_Lightcore           = ('Wham Shell Lightcore'        , Game.Swap_Force       , Element.UNKNOWN, Character.Wham_Shell               , 'FFFF', 'FFFF', 'swap-force/wham-shell-lightcore.jpg', [Tag.Lightcore])
    Punk_Shock                     = ('Punk Shock'                  , Game.Swap_Force       , Element.Water  , Character.Punk_Shock               , 'c70b', '0020', 'swap-force/punk-shock.jpg', [])
    Cynder_Series_3                = ('Cynder Series 3'             , Game.Swap_Force       , Element.UNKNOWN, Character.Cynder                   , 'FFFF', 'FFFF', 'swap-force/cynder-series-3.jpg', [])
    Green_Chop_Chop                = ('Green Chop Chop'             , Game.Swap_Force       , Element.UNKNOWN, Character.Chop_Chop                , 'FFFF', 'FFFF', 'swap-force/green-chop-chop.jpg', [Tag.Green])
    Flashwing_Lightcore            = ('Flashwing Lightcore'         , Game.Swap_Force       , Element.UNKNOWN, Character.Flashwing                , 'FFFF', 'FFFF', 'swap-force/flashwing-lightcore.jpg', [Tag.Lightcore])
    Slobber_Tooth                  = ('Slobber Tooth'               , Game.Swap_Force       , Element.Earth  , Character.Slobber_Tooth            , 'ba0b', '0020', 'swap-force/slobber-tooth.jpg', [])
    Warnado_Lightcore              = ('Warnado Lightcore'           , Game.Swap_Force       , Element.UNKNOWN, Character.Warnado                  , 'FFFF', 'FFFF', 'swap-force/warnado-lightcore.jpg', [Tag.Lightcore])
    Jolly_Bumble_Blast             = ('Jolly Bumble Blast'          , Game.Swap_Force       , Element.Life   , Character.Bumble_Blast             , 'be0b', '0224', 'swap-force/jolly-bumble-blast.jpg', [Tag.Jolly])
    Pop_Thorn                      = ('Pop Thorn'                   , Game.Swap_Force       , Element.Air    , Character.Pop_Thorn                , 'b90b', '0020', 'swap-force/pop-thorn.jpg', [])
    Green_Flame_Fire_Bone_Hot_Dog  = ('Green Flame Fire Bone Hot Dog', Game.Swap_Force       , Element.UNKNOWN, Character.Flame_Fire_Bone_Hot_Dog  , 'FFFF', 'FFFF', 'swap-force/green-flame-fire-bone-hot-dog.jpg', [Tag.Green])
    Jet_Vac_Series_2               = ('Jet Vac Series 2'            , Game.Swap_Force       , Element.UNKNOWN, Character.Jet_Vac                  , 'FFFF', 'FFFF', 'swap-force/jet-vac-series-2.jpg', [])
    Snowderdash                    = ('Snowderdash'                 , Game.Swap_Force       , Element.UNKNOWN, Character.Snowderdash              , 'FFFF', 'FFFF', 'swap-force/snowderdash.jpg', [])
    Scorp                          = ('Scorp'                       , Game.Swap_Force       , Element.Earth  , Character.Scorp                    , 'bb0b', '0020', 'swap-force/scorp.jpg'   , [])
    Drobit_Mini                    = ('Drobit Mini'                 , Game.Trap_Team        , Element.UNKNOWN, Character.Drobit                   , 'FFFF', 'FFFF', 'trap-team/drobit-mini.jpg', [Tag.Mini])
    Gearshift                      = ('Gearshift'                   , Game.Trap_Team        , Element.UNKNOWN, Character.Gearshift                , 'FFFF', 'FFFF', 'trap-team/gearshift.jpg', [])
    Jawbreaker                     = ('Jawbreaker'                  , Game.Trap_Team        , Element.Tech   , Character.Jawbreaker               , 'd601', '0030', 'trap-team/jawbreaker.jpg', [])
    Bat_Spin                       = ('Bat Spin'                    , Game.Trap_Team        , Element.Undead , Character.Bat_Spin                 , 'e001', '0030', 'trap-team/bat-spin.jpg' , [])
    Cobra_Cadabra                  = ('Cobra Cadabra'               , Game.Trap_Team        , Element.Magic  , Character.Cobra_Cadabra            , 'd501', '0030', 'trap-team/cobra-cadabra.jpg', [])
    Enigma                         = ('Enigma'                      , Game.Trap_Team        , Element.Magic  , Character.Enigma                   , 'd301', '0030', 'trap-team/enigma.jpg'   , [])
    Thumpling_Mini                 = ('Thumpling Mini'              , Game.Trap_Team        , Element.UNKNOWN, Character.Thumpling                , 'FFFF', 'FFFF', 'trap-team/thumpling-mini.jpg', [Tag.Mini])
    Flip_Wreck                     = ('Flip Wreck'                  , Game.Trap_Team        , Element.Water  , Character.Flip_Wreck               , 'd001', '0030', 'trap-team/flip-wreck.jpg', [])
    Terrabite_Mini                 = ('Terrabite Mini'              , Game.Trap_Team        , Element.UNKNOWN, Character.Terrabite                , 'FFFF', 'FFFF', 'trap-team/terrabite-mini.jpg', [Tag.Mini])
    Minijini_Mini                  = ('Minijini Mini'               , Game.Trap_Team        , Element.UNKNOWN, Character.Minijini                 , 'FFFF', 'FFFF', 'trap-team/minijini-mini.jpg', [Tag.Mini])
    Fist_Bump                      = ('Fist Bump'                   , Game.Trap_Team        , Element.Earth  , Character.Fist_Bump                , 'c801', '0030', 'trap-team/fist-bump.jpg', [])
    Weeruptor_Mini                 = ('Weeruptor Mini'              , Game.Trap_Team        , Element.UNKNOWN, Character.Weeruptor                , 'FFFF', 'FFFF', 'trap-team/weeruptor-mini.jpg', [Tag.Mini])
    Funny_Bone                     = ('Funny Bone'                  , Game.Trap_Team        , Element.Undead , Character.Funny_Bone               , 'e101', '0030', 'trap-team/funny-bone.jpg', [])
    Trail_Blazer                   = ('Trail Blazer'                , Game.Trap_Team        , Element.Fire   , Character.Trail_Blazer             , 'cc01', '0030', 'trap-team/trail-blazer.jpg', [])
    Bushwhack                      = ('Bushwhack'                   , Game.Trap_Team        , Element.Life   , Character.Bushwhack                , 'da01', '0030', 'trap-team/bushwhack.jpg', [])
    Echo                           = ('Echo'                        , Game.Trap_Team        , Element.Water  , Character.Echo                     , 'd101', '0030', 'trap-team/echo.jpg'     , [])
    Wild_Fire                      = ('Wild Fire'                   , Game.Trap_Team        , Element.UNKNOWN, Character.Wild_Fire                , 'FFFF', 'FFFF', 'trap-team/wild-fire.jpg', [])
    Dark_Food_Fight                = ('Dark Food Fight'             , Game.Trap_Team        , Element.Life   , Character.Food_Fight               , 'dc01', '0234', 'trap-team/dark-food-fight.jpg', [Tag.Dark])
    Whisper_Elf_Mini               = ('Whisper Elf Mini'            , Game.Trap_Team        , Element.UNKNOWN, Character.Whisper_Elf              , 'FFFF', 'FFFF', 'trap-team/whisper-elf-mini.jpg', [Tag.Mini])
    Winterfest_Lob_Star            = ('Winterfest Lob Star'         , Game.Trap_Team        , Element.UNKNOWN, Character.Lob_Star                 , 'FFFF', 'FFFF', 'trap-team/winterfest-lob-star.jpg', [Tag.Winterfest])
    Gill_Runt_Mini                 = ('Gill Runt Mini'              , Game.Trap_Team        , Element.UNKNOWN, Character.Gill_Runt                , 'FFFF', 'FFFF', 'trap-team/gill-runt-mini.jpg', [Tag.Mini])
    Pet_Vac_Mini                   = ('Pet Vac Mini'                , Game.Trap_Team        , Element.UNKNOWN, Character.Pet_Vac                  , 'FFFF', 'FFFF', 'trap-team/pet-vac-mini.jpg', [Tag.Mini])
    Tread_Head                     = ('Tread Head'                  , Game.Trap_Team        , Element.Tech   , Character.Tread_Head               , 'd901', '0030', 'trap-team/tread-head.jpg', [])
    Trigger_Snappy_Mini            = ('Trigger Snappy Mini'         , Game.Trap_Team        , Element.UNKNOWN, Character.Trigger_Snappy           , 'FFFF', 'FFFF', 'trap-team/trigger-snappy-mini.jpg', [Tag.Mini])
    Lob_Star                       = ('Lob Star'                    , Game.Trap_Team        , Element.Water  , Character.Lob_Star                 , 'cf01', '0030', 'trap-team/lob-star.jpg' , [])
    Thunderbolt                    = ('Thunderbolt'                 , Game.Trap_Team        , Element.Air    , Character.Thunderbolt              , 'c301', '0030', 'trap-team/thunderbolt.jpg', [])
    Blastermind_Skylanders         = ('Blastermind Skylanders'      , Game.Trap_Team        , Element.UNKNOWN, Character.Blastermind              , 'FFFF', 'FFFF', 'trap-team/blastermind-skylanders.jpg', [])
    High_Five_Skylanders           = ('High Five Skylanders'        , Game.Trap_Team        , Element.UNKNOWN, Character.High_Five                , 'FFFF', 'FFFF', 'trap-team/high-five-skylanders.jpg', [])
    Blackout                       = ('Blackout'                    , Game.Trap_Team        , Element.Dark   , Character.Blackout                 , 'e501', '0030', 'trap-team/blackout.jpg' , [])
    Knight_Light                   = ('Knight Light'                , Game.Trap_Team        , Element.Light  , Character.Knight_Light             , 'e201', '0030', 'trap-team/knight-light.jpg', [])
    Love_Potion_Pop_Fizz           = ('Love Potion Pop Fizz'        , Game.Trap_Team        , Element.UNKNOWN, Character.Pop_Fizz                 , 'FFFF', 'FFFF', 'trap-team/love-potion-pop-fizz.jpg', [Tag.Love_Potion])
    Small_Fry_Mini                 = ('Small Fry Mini'              , Game.Trap_Team        , Element.UNKNOWN, Character.Small_Fry                , 'FFFF', 'FFFF', 'trap-team/small-fry-mini.jpg', [Tag.Mini])
    Hijinx_Mini                    = ('Hijinx Mini'                 , Game.Trap_Team        , Element.UNKNOWN, Character.Hijinx                   , 'FFFF', 'FFFF', 'trap-team/hijinx-mini.jpg', [Tag.Mini])
    Gusto                          = ('Gusto'                       , Game.Trap_Team        , Element.Air    , Character.Gusto                    , 'c201', '0030', 'trap-team/gusto.jpg'    , [])
    Deja_Vu                        = ('Deja Vu'                     , Game.Trap_Team        , Element.Magic  , Character.Deja_Vu                  , 'd401', '0030', 'trap-team/deja-vu.jpg'  , [])
    Snap_Shot                      = ('Snap Shot'                   , Game.Trap_Team        , Element.Water  , Character.Snap_Shot                , 'ce01', '0030', 'trap-team/snap-shot.jpg', [])
    Food_Fight_Skylanders          = ('Food Fight Skylanders'       , Game.Trap_Team        , Element.UNKNOWN, Character.Food_Fight               , 'FFFF', 'FFFF', 'trap-team/food-fight-skylanders.jpg', [])
    Kaboom                         = ('Kaboom'                      , Game.Trap_Team        , Element.Fire   , Character.Kaboom                   , 'cb01', '0030', 'trap-team/kaboom.jpg'   , [])
    Eggsellent_Weeruptor_Skylander = ('Eggsellent Weeruptor Skylander', Game.Trap_Team        , Element.UNKNOWN, Character.Eggsellent_Weeruptor     , 'FFFF', 'FFFF', 'trap-team/eggsellent-weeruptor-skylander.jpg', [])
    Bop_Mini                       = ('Bop Mini'                    , Game.Trap_Team        , Element.UNKNOWN, Character.Bop                      , 'FFFF', 'FFFF', 'trap-team/bop-mini.jpg' , [Tag.Mini])
    Shroomboom_Series_2            = ('Shroomboom Series 2'         , Game.Trap_Team        , Element.UNKNOWN, Character.Shroomboom               , 'FFFF', 'FFFF', 'trap-team/shroomboom-series-2.jpg', [])
    Spry                           = ('Spry'                        , Game.Trap_Team        , Element.UNKNOWN, Character.Spry                     , 'FFFF', 'FFFF', 'trap-team/spry.jpg'     , [])
    Gill_Grunt_Series_4            = ('Gill Grunt Series 4'         , Game.Trap_Team        , Element.UNKNOWN, Character.Gill_Grunt               , 'FFFF', 'FFFF', 'trap-team/gill-grunt-series-4.jpg', [])
    Torch                          = ('Torch'                       , Game.Trap_Team        , Element.Fire   , Character.Torch                    , 'cd01', '0030', 'trap-team/torch.jpg'    , [])
    Head_Rush                      = ('Head Rush'                   , Game.Trap_Team        , Element.Earth  , Character.Head_Rush                , 'c701', '0030', 'trap-team/head-rush.jpg', [])
    Knight_Mare                    = ('Knight Mare'                 , Game.Trap_Team        , Element.UNKNOWN, Character.Knight_Mare              , 'FFFF', 'FFFF', 'trap-team/knight-mare.jpg', [])
    Legendary_Blades               = ('Legendary Blades'            , Game.Trap_Team        , Element.Air    , Character.Blades                   , 'c501', '0334', 'trap-team/legendary-blades.jpg', [Tag.Legendary])
    Chopper                        = ('Chopper'                     , Game.Trap_Team        , Element.Tech   , Character.Chopper                  , 'd801', '0030', 'trap-team/chopper.jpg'  , [])
    Fling_Kong                     = ('Fling Kong'                  , Game.Trap_Team        , Element.Air    , Character.Fling_Kong               , 'c401', '0030', 'trap-team/fling-kong.jpg', [])
    Short_Cut                      = ('Short Cut'                   , Game.Trap_Team        , Element.Undead , Character.Short_Cut                , 'df01', '0030', 'trap-team/short-cut.jpg', [])
    Spotlight                      = ('Spotlight'                   , Game.Trap_Team        , Element.UNKNOWN, Character.Spotlight                , 'FFFF', 'FFFF', 'trap-team/spotlight.jpg', [])
    Krypt_King                     = ('Krypt King'                  , Game.Trap_Team        , Element.Undead , Character.Krypt_King               , 'de01', '0030', 'trap-team/krypt-king.jpg', [])
    Eye_Small_Mini                 = ('Eye Small Mini'              , Game.Trap_Team        , Element.UNKNOWN, Character.Eye_Small                , 'FFFF', 'FFFF', 'trap-team/eye-small-mini.jpg', [Tag.Mini])
    Dark_Snap_Shot                 = ('Dark Snap Shot'              , Game.Trap_Team        , Element.Water  , Character.Snap_Shot                , 'ce01', '0234', 'trap-team/dark-snap-shot.jpg', [Tag.Dark])
    Breeze_Mini                    = ('Breeze Mini'                 , Game.Trap_Team        , Element.UNKNOWN, Character.Breeze                   , 'FFFF', 'FFFF', 'trap-team/breeze-mini.jpg', [Tag.Mini])
    Wallop                         = ('Wallop'                      , Game.Trap_Team        , Element.Earth  , Character.Wallop                   , 'c601', '0030', 'trap-team/wallop.jpg'   , [])
    Power_Punch_Pet_Vac_Skylander  = ('Power Punch Pet Vac Skylander', Game.Trap_Team        , Element.UNKNOWN, Character.Pet_Vac                  , 'FFFF', 'FFFF', 'trap-team/power-punch-pet-vac-skylander.jpg', [Tag.Power_Punch])
    Legendary_Jawbreaker           = ('Legendary Jawbreaker'        , Game.Trap_Team        , Element.Tech   , Character.Jawbreaker               , 'd601', '0334', 'trap-team/legendary-jawbreaker.jpg', [Tag.Legendary])
    Tuff_Luck                      = ('Tuff Luck'                   , Game.Trap_Team        , Element.Life   , Character.Tuff_Luck                , 'db01', '0030', 'trap-team/tuff-luck.jpg', [])
    Barkley_Mini                   = ('Barkley Mini'                , Game.Trap_Team        , Element.UNKNOWN, Character.Barkley                  , 'FFFF', 'FFFF', 'trap-team/barkley-mini.jpg', [Tag.Mini])
    Dark_Wildfire                  = ('Dark Wildfire'               , Game.Trap_Team        , Element.Fire   , Character.Wildfire                 , 'ca01', '0234', 'trap-team/dark-wildfire.jpg', [Tag.Dark])
    Blades                         = ('Blades'                      , Game.Trap_Team        , Element.Air    , Character.Blades                   , 'c501', '0030', 'trap-team/blades.jpg'   , [])
    Turbo_Charge_Donkey_Kong       = ('Turbo Charge Donkey Kong'    , Game.Superchargers    , Element.UNKNOWN, Character.Turbo_Charge_Donkey_Kong , 'FFFF', 'FFFF', 'superchargers/turbo-charge-donkey-kong.jpg', [])
    Bone_Bash_Roller_Brawl_Skylander = ('Bone Bash Roller Brawl Skylander', Game.Superchargers    , Element.UNKNOWN, Character.Bone_Bash_Roller_Brawl   , 'FFFF', 'FFFF', 'superchargers/bone-bash-roller-brawl-skylander.jpg', [])
    Eggcited_Thrillipede           = ('Eggcited Thrillipede'        , Game.Superchargers    , Element.UNKNOWN, Character.Eggcited_Thrillipede     , 'FFFF', 'FFFF', 'superchargers/eggcited-thrillipede.jpg', [])
    Dark_Spitfire                  = ('Dark Spitfire'               , Game.Superchargers    , Element.UNKNOWN, Character.Spitfire                 , 'FFFF', 'FFFF', 'superchargers/dark-spitfire.jpg', [Tag.Dark])
    Double_Dare_Trigger_Happy      = ('Double Dare Trigger Happy'   , Game.Superchargers    , Element.UNKNOWN, Character.Double_Dare_Trigger_Happy, 'FFFF', 'FFFF', 'superchargers/double-dare-trigger-happy.jpg', [])
    Dive_Clops                     = ('Dive Clops'                  , Game.Superchargers    , Element.UNKNOWN, Character.Dive_Clops               , 'FFFF', 'FFFF', 'superchargers/dive-clops.jpg', [])
    Spitfire_Skylander             = ('Spitfire Skylander'          , Game.Superchargers    , Element.UNKNOWN, Character.Spitfire                 , 'FFFF', 'FFFF', 'superchargers/spitfire-skylander.jpg', [])
    Steel_Plated_Smash_Hit         = ('Steel Plated Smash Hit'      , Game.Superchargers    , Element.UNKNOWN, Character.Steel_Plated_Smash_Hit   , 'FFFF', 'FFFF', 'superchargers/steel-plated-smash-hit.jpg', [])
    Deep_Dive_Gill_Grunt           = ('Deep Dive Gill Grunt'        , Game.Superchargers    , Element.UNKNOWN, Character.Deep_Dive_Gill_Grunt     , 'FFFF', 'FFFF', 'superchargers/deep-dive-gill-grunt.jpg', [])
    Autism_Skylander_Power_Blue_Splat = ('Autism Skylander Power Blue Splat', Game.Superchargers    , Element.UNKNOWN, Character.Autism_Skylander_Power_Blue_Splat, 'FFFF', 'FFFF', 'superchargers/autism-skylander-power-blue-splat.jpg', [])
    Dark_Hammer_Slammer_Bowser     = ('Dark Hammer Slammer Bowser'  , Game.Superchargers    , Element.UNKNOWN, Character.Hammer_Slammer_Bowser    , 'FFFF', 'FFFF', 'superchargers/dark-hammer-slammer-bowser.jpg', [Tag.Dark])
    Dark_Turbo_Charge_Donkey_Kong  = ('Dark Turbo Charge Donkey Kong', Game.Superchargers    , Element.UNKNOWN, Character.Turbo_Charge_Donkey_Kong , 'FFFF', 'FFFF', 'superchargers/dark-turbo-charge-donkey-kong.jpg', [Tag.Dark])
    Autism_Skylander_Power_Blue_Trigger_Happy = ('Autism Skylander Power Blue Trigger Happy', Game.Superchargers    , Element.UNKNOWN, Character.Autism_Skylander_Power_Blue_Trigger_Happy, 'FFFF', 'FFFF', 'superchargers/autism-skylander-power-blue-trigger-happy.jpg', [])
    Birthday_Bash_Big_Bubble_Pop_Fizz = ('Birthday Bash Big Bubble Pop Fizz', Game.Superchargers    , Element.UNKNOWN, Character.Birthday_Bash_Big_Bubble_Pop_Fizz, 'FFFF', 'FFFF', 'superchargers/birthday-bash-big-bubble-pop-fizz.jpg', [])
    Hurricane_Jet_Vac              = ('Hurricane Jet Vac'           , Game.Superchargers    , Element.UNKNOWN, Character.Hurricane_Jet_Vac        , 'FFFF', 'FFFF', 'superchargers/hurricane-jet-vac.jpg', [])
    Legendary_Hurricane_Jet_Vac    = ('Legendary Hurricane Jet Vac' , Game.Superchargers    , Element.UNKNOWN, Character.Hurricane_Jet_Vac        , 'FFFF', 'FFFF', 'superchargers/legendary-hurricane-jet-vac.jpg', [Tag.Legendary])
    Legendary_Bone_Bash_Roller_Brawl = ('Legendary Bone Bash Roller Brawl', Game.Superchargers    , Element.UNKNOWN, Character.Bone_Bash_Roller_Brawl   , 'FFFF', 'FFFF', 'superchargers/legendary-bone-bash-roller-brawl.jpg', [Tag.Legendary])
    Missle_Tow_Dive_Clops_Skylander = ('Missle Tow Dive Clops Skylander', Game.Superchargers    , Element.UNKNOWN, Character.Missle_Tow_Dive_Clops    , 'FFFF', 'FFFF', 'superchargers/missle-tow-dive-clops-skylander.jpg', [])
    Skylanders_Nightfall           = ('Skylanders Nightfall'        , Game.Superchargers    , Element.UNKNOWN, Character.Nightfall                , 'FFFF', 'FFFF', 'superchargers/skylanders-nightfall.jpg', [])
    Fiesta_Skylanders              = ('Fiesta Skylanders'           , Game.Superchargers    , Element.UNKNOWN, Character.Fiesta                   , 'FFFF', 'FFFF', 'superchargers/fiesta-skylanders.jpg', [])
    Shark_Shooter_Terrafin         = ('Shark Shooter Terrafin'      , Game.Superchargers    , Element.UNKNOWN, Character.Shark_Shooter_Terrafin   , 'FFFF', 'FFFF', 'superchargers/shark-shooter-terrafin.jpg', [])
    Skylanders_High_Volt           = ('Skylanders High Volt'        , Game.Superchargers    , Element.UNKNOWN, Character.High_Volt                , 'FFFF', 'FFFF', 'superchargers/skylanders-high-volt.jpg', [])
    Super_Shot_Stealth_Elf         = ('Super Shot Stealth Elf'      , Game.Superchargers    , Element.UNKNOWN, Character.Super_Shot_Stealth_Elf   , 'FFFF', 'FFFF', 'superchargers/super-shot-stealth-elf.jpg', [])
    Big_Buggle_Pop_Fizz_Skylander  = ('Big Buggle Pop Fizz Skylander', Game.Superchargers    , Element.UNKNOWN, Character.Big_Buggle_Pop_Fizz      , 'FFFF', 'FFFF', 'superchargers/big-buggle-pop-fizz-skylander.jpg', [])
    Thrillipede_Skylander          = ('Thrillipede Skylander'       , Game.Superchargers    , Element.UNKNOWN, Character.Thrillipede              , 'FFFF', 'FFFF', 'superchargers/thrillipede-skylander.jpg', [])
    Stormblade_Skylander           = ('Stormblade Skylander'        , Game.Superchargers    , Element.UNKNOWN, Character.Stormblade               , 'FFFF', 'FFFF', 'superchargers/stormblade-skylander.jpg', [])
    Skylanders_Smash_Hit           = ('Skylanders Smash Hit'        , Game.Superchargers    , Element.UNKNOWN, Character.Smash_Hit                , 'FFFF', 'FFFF', 'superchargers/skylanders-smash-hit.jpg', [])
    Splat_Skylander                = ('Splat Skylander'             , Game.Superchargers    , Element.UNKNOWN, Character.Splat                    , 'FFFF', 'FFFF', 'superchargers/splat-skylander.jpg', [])
    Astroblast_Skylanders_Figure   = ('Astroblast Skylanders Figure', Game.Superchargers    , Element.UNKNOWN, Character.Astroblast_Skylanders_Figure, 'FFFF', 'FFFF', 'superchargers/astroblast-skylanders-figure.jpg', [])
    Snow_Brite_Stormblade_Skylanders = ('Snow Brite Stormblade Skylanders', Game.Superchargers    , Element.UNKNOWN, Character.Snow_Brite_Stormblade    , 'FFFF', 'FFFF', 'superchargers/snow-brite-stormblade-skylanders.jpg', [])
    Skylanders_Lava_Lance_Eruptor  = ('Skylanders Lava Lance Eruptor', Game.Superchargers    , Element.UNKNOWN, Character.Lava_Lance_Eruptor       , 'FFFF', 'FFFF', 'superchargers/skylanders-lava-lance-eruptor.jpg', [])
    Frightful_Fiesta               = ('Frightful Fiesta'            , Game.Superchargers    , Element.UNKNOWN, Character.Frightful_Fiesta         , 'FFFF', 'FFFF', 'superchargers/frightful-fiesta.jpg', [])
    Legendary_Astroblast_Skylanders_Superchargers_Figure = ('Legendary Astroblast Skylanders Superchargers Figure', Game.Superchargers    , Element.UNKNOWN, Character.Astroblast_Skylanders_Superchargers_Figure, 'FFFF', 'FFFF', 'superchargers/legendary-astroblast-skylanders-superchargers-figure.jpg', [Tag.Legendary])
    Hammer_Slam_Bowser             = ('Hammer Slam Bowser'          , Game.Superchargers    , Element.UNKNOWN, Character.Hammer_Slam_Bowser       , 'FFFF', 'FFFF', 'superchargers/hammer-slam-bowser.jpg', [])
    Dark_Super_Shot_Stealth_Elf    = ('Dark Super Shot Stealth Elf' , Game.Superchargers    , Element.UNKNOWN, Character.Super_Shot_Stealth_Elf   , 'FFFF', 'FFFF', 'superchargers/dark-super-shot-stealth-elf.jpg', [Tag.Dark])
    def __init__(self, namestring, game, element, character, toytype, subtype, image, tags):
        self.namestring = namestring
        self.game = game
        self.element = element
        self.character = character
        self.toytype = bytes.fromhex(toytype)
        self.subtype = bytes.fromhex(subtype)
        self.image = image
        self.tags = tags
